//! M6 cognition parity vs the Python golden capture
//! (`tests/parity/fixtures/cognition_golden.json`, regenerated by
//! `PYTHONPATH=. python3 tests/parity/cognition_capture.py`).
//!
//! Covered surfaces: validate_intent (9 cases incl. the truthy-NOOP
//! subtlety), Intent fingerprints (incl. message carriers with fixed
//! identity fields), Observation render()/prompt_seed(), outcomes_from_
//! results, and the PolicyCognition adapter path over a stand-in context
//! whose facts replicate the capture's kernel.

use arena::cognition::{
    outcomes_from_results, validate_intent, Cognition, Control, Intent, Observation, Outcome,
    PolicyCognition, ToolCall, ToolResultView,
};
use arena::graph::TaskSpec;
use arena::msg::{EventType, Message};
use arena::policy::{NeedsSpecialist, PolicyContext, SimulatedWork, WaitForArtifacts};
use arena::sys::json::{parse, JMap, JValue};
use std::path::PathBuf;

fn golden() -> JValue {
    let p: PathBuf = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/parity/fixtures/cognition_golden.json"
    )
    .into();
    parse(&std::fs::read_to_string(p).expect("golden file present")).expect("golden parses")
}

fn jstr(s: &str) -> JValue {
    JValue::Str(s.to_string())
}

fn jmap(pairs: Vec<(&str, JValue)>) -> JMap {
    pairs.into_iter().map(|(k, v)| (k.to_string(), v)).collect()
}

fn arr_str(items: &[&str]) -> JValue {
    JValue::Arr(items.iter().map(|s| jstr(s)).collect())
}

fn calls(specs: &[(&str, &str)]) -> Vec<ToolCall> {
    // all capture calls use empty args unless the name carries an argv hint
    specs
        .iter()
        .map(|(tool, argv)| {
            let args = if argv.is_empty() {
                JMap::new()
            } else {
                jmap(vec![(
                    "argv",
                    arr_str(&argv.split(',').collect::<Vec<_>>()),
                )])
            };
            ToolCall::new(tool, args)
        })
        .collect()
}

fn intent_view(i: &Intent) -> JValue {
    JValue::Obj(jmap(vec![
        (
            "calls",
            JValue::Arr(
                i.calls
                    .iter()
                    .map(|c| {
                        JValue::Obj(jmap(vec![
                            ("tool", jstr(&c.tool)),
                            ("args", JValue::Obj(c.args.clone())),
                        ]))
                    })
                    .collect(),
            ),
        ),
        ("control", jstr(&i.control)),
        ("think", jstr(&i.think)),
        ("reason", jstr(&i.reason)),
        ("wait_for", jstr(&i.wait_for)),
        ("max_calls", JValue::Int(i.max_calls)),
    ]))
}

fn arr_len(v: &JValue) -> usize {
    match v {
        JValue::Arr(a) => a.len(),
        other => panic!("expected array, got {other:?}"),
    }
}

fn notes_view(notes: &[String]) -> JValue {
    JValue::Arr(notes.iter().map(|n| jstr(n)).collect())
}

// ------------------------------------------------------------------ context

/// Stand-in replicating the capture kernel's facts for agent be_01.
struct CapCtx {
    task: Option<TaskSpec>,
    artifacts: Vec<String>,
    producers: Vec<(String, String)>,
    step: i64,
}

impl CapCtx {
    fn backend(task: &str) -> CapCtx {
        let mut t = TaskSpec::new(task, "backend API", "backend");
        if task == "t_be" {
            t.est_work = 2.0;
            t.produces = vec!["out/api.md".into()];
            t.consumes = vec!["in/schema.sql".into()];
        }
        CapCtx {
            task: Some(t),
            artifacts: vec![],
            producers: vec![],
            step: 0,
        }
    }
}

impl PolicyContext for CapCtx {
    fn agent_id(&self) -> &str {
        "be_01"
    }
    fn step_index(&self) -> i64 {
        self.step
    }
    fn state(&self) -> String {
        "WORKING".to_string()
    }
    fn llm_available(&self) -> bool {
        false
    }
    fn task(&self) -> Option<&TaskSpec> {
        self.task.as_ref()
    }
    fn task_id(&self) -> Option<String> {
        self.task.as_ref().map(|t| t.task_id.as_str().to_string())
    }
    fn all_unmet(&self) -> Vec<String> {
        match &self.task {
            Some(t) => t
                .consumes
                .iter()
                .filter(|a| !self.artifacts.contains(a))
                .cloned()
                .collect(),
            None => vec![],
        }
    }
    fn unmet_artifacts(&self) -> Vec<String> {
        self.all_unmet()
    }
    fn consumed_ready(&self) -> Vec<String> {
        match &self.task {
            Some(t) => t
                .consumes
                .iter()
                .filter(|a| self.artifacts.contains(a))
                .cloned()
                .collect(),
            None => vec![],
        }
    }
    fn roster_roles(&self) -> Vec<String> {
        vec!["backend".to_string()]
    }
    fn producer_roles(&self, artifact: &str) -> Vec<String> {
        self.producers
            .iter()
            .filter(|(a, _)| a == artifact)
            .map(|(_, r)| r.clone())
            .collect()
    }
    fn log(&mut self, _text: &str) {}
    fn poll_hit(&mut self) -> Result<i64, arena::bus::BusError> {
        Ok(0)
    }
    fn self_msg(&self, msg_type: EventType, body: &str, payload: JMap) -> Message {
        // the capture's ActorContext.self_msg: to parent, task_id defaulted
        let mut m = Message::new(msg_type, "be_01", "parent");
        m.body = body.to_string();
        m.payload = payload;
        if let Some(t) = &self.task {
            m.task_id = Some(t.task_id.clone());
        }
        m
    }
    fn request_specialist(
        &self,
        _role: &str,
        _reason: &str,
        _skills: &[String],
        _inputs: &[String],
        _outputs: &[String],
        _est_work: f64,
        _capability_class: &str,
    ) -> Message {
        self.self_msg(EventType::SpawnAgentRequest, "", JMap::new())
    }
}

fn sem_msg(m: Option<&Message>) -> JValue {
    match m {
        None => JValue::Null,
        Some(m) => JValue::Obj(jmap(vec![
            ("type", jstr(m.msg_type.as_str())),
            ("from", jstr(m.from_actor.as_str())),
            ("to", jstr(m.to_actor.as_str())),
            ("body", jstr(&m.body)),
            (
                "task_id",
                m.task_id.as_deref().map(jstr).unwrap_or(JValue::Null),
            ),
            ("depth", JValue::Int(m.causal_depth)),
            (
                "payload_keys",
                JValue::Arr(m.payload.keys().map(|k| jstr(k)).collect()),
            ),
        ])),
    }
}

// -------------------------------------------------------------------- tests

#[test]
fn validate_intent_matches_python_golden() {
    let g = golden();
    let mut idx = 0usize;

    macro_rules! cap {
        ($tag:expr, $intent:expr, $allowed:expr) => {{
            let (got, notes) = validate_intent($intent, $allowed, 4);
            let want = g.get("validate_intent").unwrap().idx(idx).unwrap();
            assert_eq!(
                want.get("case").unwrap().as_str().unwrap(),
                $tag,
                "case order"
            );
            assert_eq!(
                intent_view(&got),
                want.get("intent").unwrap().clone(),
                "intent {}",
                $tag
            );
            assert_eq!(
                notes_view(&notes),
                want.get("notes").unwrap().clone(),
                "notes {}",
                $tag
            );
            idx += 1;
        }};
    }

    // valid
    let mut i = Intent::new();
    i.calls = calls(&[("bash", "ls,-la"), ("read", "")]);
    i.control = Control::PUBLISH.into();
    i.think = "checking".into();
    i.reason = "publish after check".into();
    let allowed = vec!["bash".to_string(), "read".to_string()];
    cap!("valid", Some(i), &allowed);

    // missing
    cap!("missing", None, &["bash".to_string()]);

    // unknown control (calls+think survive; verb/publish dropped)
    let mut i = Intent::new();
    i.calls = calls(&[("bash", "")]);
    i.control = "run".into();
    i.think = "original thought".into();
    i.reason = "full speed".into();
    i.wait_for = "x".into();
    cap!("unknown_control", Some(i), &["bash".to_string()]);

    // unauthorized tools, no control -> paper-trail NOOP
    let mut i = Intent::new();
    i.calls = calls(&[("rm", ""), ("curl", "")]);
    cap!("unauthorized_all", Some(i), &["bash".to_string()]);

    // unauthorized + valid control -> calls filtered, verb kept
    let mut i = Intent::new();
    i.calls = calls(&[("rm", ""), ("bash", "")]);
    i.control = Control::WAIT.into();
    cap!("unauthorized_some", Some(i), &["bash".to_string()]);

    // truncation (6 allowed, max 4)
    let mut i = Intent::new();
    i.calls = calls(&[
        ("t0", ""),
        ("t1", ""),
        ("t2", ""),
        ("t3", ""),
        ("t4", ""),
        ("t5", ""),
    ]);
    let allowed: Vec<String> = (0..6).map(|n| format!("t{n}")).collect();
    cap!("truncated", Some(i), &allowed);

    // mixed: one refused, six allowed -> 6>4
    let mut i = Intent::new();
    i.calls = calls(&[
        ("t0", ""),
        ("t1", ""),
        ("t2", ""),
        ("t3", ""),
        ("t4", ""),
        ("t5", ""),
        ("t6", ""),
    ]);
    cap!("mixed_refuse_truncate", Some(i), &allowed);

    // malformed: missing tool -> "" -> refused
    let dict = JValue::Obj(jmap(vec![(
        "args",
        JValue::Obj(jmap(vec![("x", JValue::Int(1))])),
    )]));
    let i = Intent::of(&[dict], Control::NONE, "");
    cap!("malformed_empty_tool", Some(i), &["bash".to_string()]);

    // unknown control AND all calls refused -> rebuilt intent (NOOP is truthy)
    let mut i = Intent::new();
    i.calls = calls(&[("rm", "")]);
    i.control = "run".into();
    cap!(
        "unknown_control_and_refused",
        Some(i),
        &["bash".to_string()]
    );

    assert_eq!(idx, g.get("validate_intent").map(arr_len).unwrap());
}

#[test]
fn fingerprints_match_python_golden() {
    let g = golden();
    let mut idx = 0usize;
    macro_rules! cap {
        ($tag:expr, $i:expr) => {{
            let i: Intent = $i;
            let want = g.get("fingerprints").unwrap().idx(idx).unwrap();
            assert_eq!(want.get("case").unwrap().as_str().unwrap(), $tag);
            assert_eq!(
                i.fingerprint(),
                want.get("fingerprint").unwrap().as_str().unwrap(),
                "fp {}",
                $tag
            );
            assert_eq!(
                i.is_noop(),
                want.get("is_noop").unwrap().as_bool().unwrap(),
                "noop {}",
                $tag
            );
            idx += 1;
        }};
    }
    cap!("bare", Intent::new());
    cap!("wait", {
        let mut i = Intent::new();
        i.control = Control::WAIT.into();
        i.wait_for = "db/schema.sql".into();
        i
    });
    cap!("wait_reason", {
        let mut i = Intent::new();
        i.control = Control::WAIT.into();
        i.wait_for = "db/schema.sql".into();
        i.reason = "parked".into();
        i
    });
    cap!("calls", {
        let mut i = Intent::new();
        i.calls = calls(&[("bash", "ls"), ("read", "")]);
        i.control = Control::NOOP.into();
        i
    });
    cap!("spawn_dict", {
        let mut i = Intent::new();
        i.control = Control::SPAWN_REQUEST.into();
        i.spawn = jmap(vec![("requested_role", jstr("database"))]);
        i
    });
    cap!("artifacts", {
        let mut i = Intent::new();
        i.control = Control::COMPLETE.into();
        i.publish = jmap(vec![("artifacts", arr_str(&["out/api.md"]))]);
        i
    });
    cap!("publish_msg", {
        let mut m = Message::new(EventType::ArtifactPublished, "a_01", "broadcast");
        m.body = "out/api.md ready".into();
        m.mid = "m-pub00000001".into();
        m.correlation_id = "c-pub00000001".into();
        m.ts = 1.25;
        m.causal_depth = 2;
        let mut i = Intent::new();
        i.control = Control::PUBLISH.into();
        i.msg = Some(m);
        i
    });
    cap!("spawn_msg", {
        let mut m = Message::new(EventType::SpawnAgentRequest, "a_01", "parent");
        m.body = "need a dba".into();
        m.mid = "m-spw00000001".into();
        m.correlation_id = "c-spw00000001".into();
        m.ts = 2.0;
        m.causal_depth = 3;
        m.task_id = Some("t_be".into());
        let mut i = Intent::new();
        i.control = Control::SPAWN_REQUEST.into();
        i.msg = Some(m);
        i
    });
    assert_eq!(idx, g.get("fingerprints").map(arr_len).unwrap());
}

#[test]
fn observation_render_and_prompt_seed_match_python_golden() {
    let g = golden();
    let mk = |tool: &str, ok: bool, exit: Option<i64>, data: JMap, refused: &str| Outcome {
        tool: tool.into(),
        ok,
        exit_code: exit,
        data,
        refused: refused.into(),
        ..Default::default()
    };
    let empty = JMap::new;
    let obs = Observation {
        agent_id: "a_01".into(),
        role: "worker".into(),
        goal: "build the thing".into(),
        task: jmap(vec![
            ("task_id", jstr("t_09")),
            ("status", jstr("OPEN")),
            ("produces", arr_str(&["db/schema.sql"])),
            ("verify", arr_str(&["pytest", "ruff"])),
        ]),
        step_index: 3,
        unmet: vec!["api/openapi.json".into()],
        workspace: jmap(vec![
            ("files", arr_str(&["a.py", "b.py"])),
            ("dirty", JValue::Bool(true)),
        ]),
        recent: vec![
            mk("bash", true, Some(0), jmap(vec![("n", JValue::Int(3))]), ""),
            mk("write", false, None, empty(), "path outside workspace"),
        ],
        history: (0..9)
            .map(|n| mk(&format!("h{n}"), true, None, empty(), ""))
            .collect(),
        notes: vec!["note one".into()],
        state: "WORKING".into(),
        tool_schemas: vec![jmap(vec![("tool", jstr("bash"))])],
        graph_view: vec![jmap(vec![("task_id", jstr("t_1"))])],
        budget: jmap(vec![("steps_left", JValue::Int(3))]),
        transcript_len: 12,
        ..Default::default()
    };
    assert_eq!(
        obs.render(),
        g.get("render").unwrap().as_str().unwrap_or_default()
    );
    assert_eq!(
        JValue::Obj(obs.prompt_seed()),
        g.get("prompt_seed").unwrap().clone(),
        "prompt_seed"
    );
}

#[test]
fn outcomes_from_results_match_python_golden() {
    let g = golden();
    let rs = vec![
        ToolResultView {
            tool: "bash".into(),
            ok: true,
            exit_code: Some(2),
            block: "== bash ==\nls\n".into(),
            data: jmap(vec![
                ("n", JValue::Int(3)),
                ("ratio", JValue::Float(0.5)),
                ("name", jstr("x")),
                ("flag", JValue::Bool(false)),
                ("nested", JValue::Obj(JMap::new())),
                ("listy", JValue::Arr(vec![])),
            ]),
            ..Default::default()
        },
        ToolResultView {
            block: "hidden".into(),
            data: jmap(vec![("keep", jstr("v"))]),
            ..Default::default()
        },
        ToolResultView {
            tool: "write".into(),
            refused: "outside workspace".into(),
            rid: "r-1".into(),
            ..Default::default()
        },
    ];
    let out = outcomes_from_results(&rs);
    let got = JValue::Arr(out.iter().map(|o| JValue::Obj(o.to_dict())).collect());
    assert_eq!(got, g.get("outcomes").unwrap().clone(), "outcomes");
}

#[test]
fn policy_cognition_adapter_matches_python_golden() {
    let g = golden();
    let mut idx = 0usize;
    macro_rules! cap {
        ($tag:expr, $policy:expr, $ctx:expr, $step:expr) => {{
            let obs = Observation {
                agent_id: "be_01".into(),
                role: "backend".into(),
                step_index: $step,
                state: "WORKING".into(),
                ..Default::default()
            };
            let mut ctx: CapCtx = $ctx;
            ctx.step = $step;
            let mut cog = PolicyCognition::new(Box::new($policy), "be_01");
            let intent = cog.decide(&obs, &mut ctx).expect("decide");
            let (validated, notes) = validate_intent(Some(intent.clone()), &[], 4);
            let want = g.get("adapter").unwrap().idx(idx).unwrap();
            assert_eq!(
                want.get("case").unwrap().as_str().unwrap(),
                $tag,
                "case order"
            );
            assert_eq!(
                intent_view(&intent),
                want.get("intent").unwrap().clone(),
                "intent {}",
                $tag
            );
            assert_eq!(
                sem_msg(intent.msg.as_ref()),
                want.get("semantic_msg").unwrap().clone(),
                "semantic msg {}",
                $tag
            );
            assert_eq!(
                intent.wait_for,
                want.get("wait_for").unwrap().as_str().unwrap_or_default(),
                "wait_for {}",
                $tag
            );
            assert_eq!(
                validated.control,
                want.get("validated_control")
                    .unwrap()
                    .as_str()
                    .unwrap_or_default(),
                "validated {}",
                $tag
            );
            assert_eq!(
                notes_view(&notes),
                want.get("notes").unwrap().clone(),
                "notes {}",
                $tag
            );
            idx += 1;
        }};
    }
    cap!(
        "sim/step0",
        SimulatedWork::default(),
        CapCtx::backend("t_be"),
        0
    );
    cap!(
        "sim/step3",
        SimulatedWork::default(),
        CapCtx::backend("t_be"),
        3
    );
    cap!(
        "sim/step4",
        SimulatedWork::default(),
        CapCtx::backend("t_be"),
        4
    );
    cap!(
        "wait/unmet",
        WaitForArtifacts::default(),
        CapCtx::backend("t_be"),
        0
    );
    let mut met = CapCtx::backend("t_be");
    met.artifacts = vec!["in/schema.sql".into()];
    met.producers = vec![("in/schema.sql".to_string(), "data".to_string())];
    cap!("wait/met", WaitForArtifacts::default(), met, 1);
    cap!(
        "specialist/ask",
        NeedsSpecialist::with_detect_from("data"),
        CapCtx::backend("t_be"),
        2
    );
    assert_eq!(idx, g.get("adapter").map(arr_len).unwrap());

    // adapter cognition fingerprint (obj_id excluded: memory address)
    let cog = PolicyCognition::new(Box::new(NeedsSpecialist::with_detect_from("data")), "be_01");
    assert_eq!(
        cog.name(),
        g.get("adapter_cognition")
            .unwrap()
            .get("name")
            .unwrap()
            .as_str()
            .unwrap_or_default()
    );
    assert_eq!(
        cog.model_id,
        g.get("adapter_cognition")
            .unwrap()
            .get("model")
            .unwrap()
            .as_str()
            .unwrap_or_default()
    );
    let fp = cog.fingerprint();
    let got = JValue::Obj(
        fp.iter()
            .filter(|(k, _)| k.as_str() != "obj_id")
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect(),
    );
    assert_eq!(
        got,
        g.get("adapter_cognition")
            .unwrap()
            .get("fingerprint_sans_obj_id")
            .unwrap()
            .clone()
    );
}
