//! Journal replay parity: the Rust `Journal` must reproduce the Python golden
//! fixtures exactly — chain verification passes, and `fold()` rebuilt from the
//! log alone equals the `fold.json` the Python run wrote (per top-level
//! section, compared in canonical JSON form).
//!
//! Fixtures are generated by `python3 tests/parity/capture.py` (commit f888427);
//! regenerate to refresh. Comparison notes:
//! - keys are structurally compared after canonicalization, so dict ordering
//!   in the fixture file itself is irrelevant;
//! - `events` is a count and `meta.tick_ts` the last row ts — both covered.

use arena::journal::Journal;
use arena::sys::json::{parse, JValue};
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR points at the crate root when run by cargo
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn fixture(name: &str) -> PathBuf {
    repo_root().join("tests/parity/fixtures").join(name)
}

/// Copy the fixture journal to a temp path so the golden file is never
/// touched (SQLite may write -wal/-shm even on read paths).
fn temp_copy(src: &Path, tag: &str) -> PathBuf {
    static COUNTER: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    let n = COUNTER.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
    let dst = std::env::temp_dir().join(format!(
        "arena-parity-{}-{}-{}.db",
        tag,
        std::process::id(),
        n
    ));
    std::fs::copy(src, &dst).expect("copy fixture journal");
    dst
}

fn canon(v: &JValue) -> String {
    v.to_canon_string()
}

fn section_diff(name: &str, got: &JValue, want: &JValue) {
    if got == want {
        return;
    }
    let g = canon(got);
    let w = canon(want);
    // first divergence for a readable failure
    let mut idx: usize = 0;
    for (a, b) in g.chars().zip(w.chars()) {
        if a != b {
            break;
        }
        idx += 1;
    }
    let lo = idx.saturating_sub(60);
    panic!(
        "fold section `{name}` diverged at byte {idx}:\n  got:  ...{}...\n  want: ...{}...",
        &g[lo..(idx + 90).min(g.len())],
        &w[lo..(idx + 90).min(w.len())],
    );
}

fn check_fixture(dir: &str, journal_rel: &str, fold_rel: Option<&str>) {
    let src = fixture(dir).join(journal_rel);
    assert!(src.exists(), "missing fixture journal {src:?}");
    let tmp = temp_copy(&src, dir.replace('/', "_").as_str());
    let j = Journal::open_file(&tmp, None).expect("open journal");

    let (ok, at, n) = j.verify_chain().expect("verify chain");
    assert!(ok, "{dir}: chain broken at seq {at} ({n} rows checked)");

    if let Some(fold_rel) = fold_rel {
        let fold_path = fixture(dir).join(fold_rel);
        let want = parse(&std::fs::read_to_string(&fold_path).expect("read fold.json"))
            .expect("parse fold.json");
        let got = JValue::Obj(j.fold().expect("fold"));
        let want_obj = match &want {
            JValue::Obj(m) => m.clone(),
            _ => panic!("fold.json is not an object"),
        };
        let got_obj = match &got {
            JValue::Obj(m) => m.clone(),
            _ => panic!("fold() is not an object"),
        };
        for key in [
            "agents",
            "tasks",
            "artifacts",
            "claims",
            "waits",
            "requests",
            "events",
            "meta",
        ] {
            let w = want_obj.get(key).cloned().unwrap_or(JValue::Null);
            let g = got_obj.get(key).cloned().unwrap_or(JValue::Null);
            section_diff(key, &g, &w);
        }
        // no extra sections on either side
        let want_keys: Vec<&String> = want_obj.keys().collect();
        let got_keys: Vec<&String> = got_obj.keys().collect();
        assert_eq!(want_keys, got_keys, "{dir}: fold sections differ");
    }
    std::fs::remove_file(&tmp).ok();
}

#[test]
fn replay_saas() {
    check_fixture("saas", "journal.db", Some("fold.json"));
}

#[test]
fn replay_ml() {
    check_fixture("ml", "journal.db", Some("fold.json"));
}

#[test]
fn replay_midrun_spawn_override() {
    check_fixture("midrun", "journal.db", Some("fold.json"));
}

#[test]
fn replay_crash_resume_phase1() {
    check_fixture("crash_resume", "journal.db", Some("fold.json"));
}

#[test]
fn replay_crash_resume_phase2() {
    check_fixture("crash_resume/resumed", "journal.db", Some("fold.json"));
}

#[test]
fn replay_e2e_calc_chain() {
    // the e2e_calc scenario has no fold.json; chain integrity still must hold
    check_fixture("e2e_calc", "project/.arena/j.db", None);
}
